import { StyleSheet } from "react-native";

import { AppColors } from "@/application/providers/theme";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safe: {
      backgroundColor: colors.card,
      flex: 1,
    },
    scrollView: {
      backgroundColor: colors.background,
    },
    header: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      elevation: 2,
      flexDirection: "row",
      height: 56,
      justifyContent: "space-between",
      paddingHorizontal: 10,
      shadowColor: colors.shadow,
      shadowOffset: { height: 2, width: 0 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
    },
    headerButton: {
      alignItems: "center",
      backgroundColor: colors.button,
      borderRadius: 8,
      height: 42,
      justifyContent: "center",
      width: 42,
    },
    headerSpacer: {
      height: 42,
      width: 42,
    },
    headerIcon: {
      color: colors.primaryText,
      fontSize: 30,
      fontWeight: "700",
      lineHeight: 36,
    },
    logo: {
      color: colors.primaryText,
      fontSize: 22,
      fontWeight: "900",
      letterSpacing: 0,
    },
    content: {
      paddingBottom: 32,
      paddingHorizontal: 20,
      paddingTop: 24,
    },
    modeRow: {
      alignSelf: "center",
      backgroundColor: colors.button,
      borderRadius: 8,
      flexDirection: "row",
      gap: 4,
      marginBottom: 20,
      maxWidth: 420,
      padding: 4,
      width: "100%",
    },
    modeButton: {
      alignItems: "center",
      borderRadius: 7,
      flex: 1,
      justifyContent: "center",
      minHeight: 38,
      paddingHorizontal: 4,
    },
    modeButtonActive: {
      backgroundColor: colors.card,
    },
    modeButtonText: {
      color: colors.secondaryText,
      fontSize: 13,
      fontWeight: "900",
      textAlign: "center",
    },
    modeButtonTextActive: {
      color: colors.primaryText,
    },
    friendsToggleBox: {
      alignSelf: "center",
      backgroundColor: colors.button,
      borderRadius: 8,
      flexDirection: "row",
      marginBottom: 16,
      maxWidth: 240,
      padding: 4,
      width: "100%",
    },
    friendsToggleBtn: {
      alignItems: "center",
      borderRadius: 6,
      flex: 1,
      justifyContent: "center",
      paddingVertical: 6,
    },
    friendsToggleActive: {
      backgroundColor: colors.card,
      elevation: 1,
      shadowColor: colors.shadow,
      shadowOffset: { height: 1, width: 0 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
    },
    friendsToggleText: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    friendsToggleTextActive: {
      color: colors.primaryText,
    },
    sectionTitle: {
      color: colors.primaryText,
      fontSize: 18,
      fontWeight: "900",
      letterSpacing: 0,
      marginBottom: 14,
      textAlign: "center",
    },
    board: {
      alignSelf: "center",
      gap: 10,
      maxWidth: 560,
      width: "100%",
    },
    myRankBox: {
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      marginBottom: 14,
      maxWidth: 560,
      paddingHorizontal: 14,
      paddingVertical: 12,
      width: "100%",
    },
    myRankLabel: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "900",
      marginBottom: 3,
    },
    myRankValue: {
      color: colors.primaryText,
      fontSize: 17,
      fontWeight: "900",
    },
    row: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      elevation: 1,
      flexDirection: "row",
      minHeight: 70,
      paddingHorizontal: 12,
      paddingVertical: 10,
      shadowColor: colors.shadow,
      shadowOffset: { height: 2, width: 0 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
    },
    rank: {
      color: colors.accent,
      fontSize: 20,
      fontWeight: "900",
      textAlign: "center",
      width: 34,
    },
    playerCopy: {
      flex: 1,
      minWidth: 0,
      paddingHorizontal: 10,
    },
    playerName: {
      color: colors.primaryText,
      fontSize: 17,
      fontWeight: "900",
    },
    username: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "800",
      marginTop: 2,
    },
    scoreBox: {
      alignItems: "center",
      backgroundColor: colors.button,
      borderRadius: 8,
      minWidth: 68,
      paddingHorizontal: 8,
      paddingVertical: 8,
    },
    score: {
      color: colors.primaryText,
      fontSize: 21,
      fontWeight: "900",
      lineHeight: 24,
    },
    scoreLabel: {
      color: colors.secondaryText,
      fontSize: 11,
      fontWeight: "900",
      marginTop: 2,
    },
    emptyBox: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      minHeight: 112,
      justifyContent: "center",
      padding: 18,
    },
    emptyText: {
      color: colors.secondaryText,
      fontSize: 15,
      fontWeight: "800",
      textAlign: "center",
    },
    pressed: {
      opacity: 0.64,
    },
  });
}
