import { StyleSheet } from "react-native";

import { AppColors } from "@/application/providers/theme";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    container: { flex: 1, paddingHorizontal: 20, paddingBottom: 32, paddingTop: 24 },
    header: { alignItems: "center", gap: 16, marginBottom: 26 },
    headerCopy: { alignItems: "center", gap: 5 },
    kicker: { color: colors.accent, fontSize: 15, fontWeight: "900", textAlign: "center" },
    title: { color: colors.primaryText, fontSize: 40, fontWeight: "900", textAlign: "center" },
    toolRow: { flexDirection: "row", gap: 10, justifyContent: "center" },
    toolButton: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 42,
      justifyContent: "center",
      width: 42,
    },
    profileButton: {
      alignItems: "center",
      backgroundColor: colors.accent,
      borderRadius: 8,
      height: 42,
      justifyContent: "center",
      minWidth: 42,
      paddingHorizontal: 8,
    },
    profileButtonText: { color: "#ffffff", fontSize: 13, fontWeight: "900" },
    list: { gap: 14 },
    card: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      elevation: 2,
      flexDirection: "row",
      justifyContent: "space-between",
      minHeight: 84,
      overflow: "hidden",
      paddingHorizontal: 18,
      paddingVertical: 15,
      position: "relative",
      shadowColor: colors.shadow,
      shadowOffset: { height: 3, width: 0 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
    },
    cardDisabled: { backgroundColor: colors.button },
    cardCopy: { flex: 1, paddingRight: 12 },
    cardPressed: { opacity: 0.72 },
    cardTitle: { color: colors.primaryText, fontSize: 22, fontWeight: "900" },
    cardSubtitle: { color: colors.secondaryText, fontSize: 14, fontWeight: "700", marginTop: 3 },
    cardArrow: { color: colors.accent, fontSize: 38, fontWeight: "500", lineHeight: 38 },
    cardStatus: { color: colors.disabled, fontSize: 13, fontWeight: "900" },
    doneCorner: {
      position: "absolute",
      top: 0,
      right: 0,
      backgroundColor: colors.correct,
      borderBottomLeftRadius: 7,
      paddingHorizontal: 7,
      paddingVertical: 3,
      zIndex: 1,
    },
    doneCornerText: { color: "#fff", fontSize: 11, fontWeight: "900" },
    disabledText: { color: colors.disabled },
    modalBackdrop: {
      alignItems: "center",
      backgroundColor: colors.overlay,
      flex: 1,
      justifyContent: "center",
      padding: 18,
    },
    guideModal: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      maxWidth: 520,
      padding: 18,
      width: "100%",
    },
    modalHeader: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    modalTitle: {
      color: colors.primaryText,
      fontSize: 20,
      fontWeight: "900",
      flexShrink: 1,
      paddingRight: 10,
    },
    closeButton: {
      alignItems: "center",
      backgroundColor: colors.button,
      borderRadius: 8,
      height: 36,
      justifyContent: "center",
      width: 36,
    },
    closeButtonText: { color: colors.primaryText, fontSize: 25, fontWeight: "700", lineHeight: 28 },
    guideCopy: {
      color: colors.secondaryText,
      fontSize: 14,
      fontWeight: "700",
      lineHeight: 20,
      marginBottom: 16,
    },
    guideSection: { marginBottom: 14 },
    guideLabel: { color: colors.primaryText, fontSize: 13, fontWeight: "900", marginBottom: 7 },
    guideRow: { flexDirection: "row", gap: 3, justifyContent: "center", marginBottom: 4, width: "100%" },
    guideKey: {
      alignItems: "center",
      backgroundColor: colors.key,
      borderRadius: 6,
      flex: 1,
      height: 30,
      justifyContent: "center",
      minWidth: 0,
      paddingHorizontal: 2,
    },
    guideKeyActive: { backgroundColor: colors.keyActive },
    guideKeyText: { color: colors.primaryText, fontSize: 13, fontWeight: "900" },
    guideKeyTextActive: { color: colors.card },
    guidePairs: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 2 },
    guidePairText: {
      backgroundColor: colors.button,
      borderRadius: 8,
      color: colors.primaryText,
      fontSize: 13,
      fontWeight: "900",
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
  });
}
