export function createMultiplayerStyles(colors: any, cellSize: number) {
  return {
    safe: { flex: 1, backgroundColor: colors.background },
    header: { alignItems: "center", flexDirection: "row", height: 48, justifyContent: "space-between", paddingHorizontal: 8 },
    hBtn: { alignItems: "center", height: 40, justifyContent: "center", width: 40 },
    title: { color: colors.primaryText, fontSize: 17, fontWeight: "900" },
    pressed: { opacity: 0.65 },
    emoteToggle: { backgroundColor: colors.button, borderRadius: 20 },
    emoteToggleIcon: { fontSize: 20 },
    emotePicker: { backgroundColor: colors.card, borderColor: colors.border, borderRadius: 14, borderWidth: 1, elevation: 12, flexDirection: "row", flexWrap: "wrap", gap: 8, padding: 10, position: "absolute", right: 8, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.25, shadowRadius: 10, top: 52, width: 200, zIndex: 999 },
    emoteBtn: { alignItems: "center", backgroundColor: colors.button, borderRadius: 22, height: 44, justifyContent: "center", width: 44 },
    emoteBtnIcon: { fontSize: 24 },
    oppStrip: { alignItems: "center", backgroundColor: colors.card, borderBottomWidth: 1, borderColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: 10, height: 74, overflow: "visible", paddingHorizontal: 12, paddingVertical: 8, position: "relative" },
    oppInfo: { alignItems: "center", gap: 3, width: 52 },
    oppAvatar: { alignItems: "center", borderRadius: 18, height: 36, justifyContent: "center", width: 36 },
    oppAvatarIcon: { fontSize: 18 },
    oppName: { color: colors.secondaryText, fontSize: 10, fontWeight: "700", textAlign: "center" },
    vsContainer: { width: 52, alignItems: "center", justifyContent: "center" },
    vsLabel: { color: colors.secondaryText, fontSize: 11, fontWeight: "900", letterSpacing: 1 },
    miniGrid: { flex: 1, gap: 3, justifyContent: "center", alignItems: "center" },
    miniRow: { flexDirection: "row", gap: 3 },
    miniCell: { borderRadius: 2, height: 9, width: 9 },
    miniCircle: { borderRadius: 6, height: 12, width: 12 },
    turnBanner: { paddingVertical: 8, alignItems: "center", justifyContent: "center", backgroundColor: colors.card, borderBottomWidth: 1, borderColor: colors.border },
    waitingText: { color: colors.secondaryText, fontSize: 13, fontWeight: "700" },
    timerText: { color: colors.primaryText, fontSize: 15, fontWeight: "800" },
    floatEmote: { elevation: 30, fontSize: 36, position: "absolute", top: 4, zIndex: 30 },
    floatLeft: { left: 10 },
    floatRight: { right: 10 },
    myGrid: { alignItems: "center", flex: 1, gap: 5, justifyContent: "center", paddingHorizontal: 16 },
    gridRow: { flexDirection: "row", gap: 5 },
    gridCell: { alignItems: "center", borderRadius: 5, borderWidth: 2, height: cellSize, justifyContent: "center", width: cellSize },
    cellLetter: { color: colors.primaryText, fontSize: Math.round(cellSize * 0.5), fontWeight: "900" },
    cellLetterWhite: { color: "#ffffff" },
    andazebiContainer: { flex: 1, width: "100%", justifyContent: "center", gap: 20 },
    promptCard: { backgroundColor: colors.card, padding: 20, borderRadius: 16, borderWidth: 1, borderColor: colors.border, elevation: 4, shadowColor: "#000", shadowOpacity: 0.1, shadowRadius: 6, shadowOffset: { width: 0, height: 3 } },
    promptText: { fontSize: 20, color: colors.primaryText, fontWeight: "800", textAlign: "center", lineHeight: 28 },
    hintText: { fontSize: 14, color: colors.secondaryText, fontWeight: "600", textAlign: "center", marginTop: 12 },
    historyContainer: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8 },
    historyBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, borderWidth: 1, borderColor: colors.border },
    historyCorrect: { backgroundColor: colors.correct, borderColor: colors.correct },
    historyWrong: { backgroundColor: colors.absent, borderColor: colors.absent },
    historyText: { color: colors.primaryText, fontSize: 14, fontWeight: "700" },
    andazebiInputContainer: { flexDirection: "row", gap: 10, justifyContent: "center", flexWrap: "wrap", marginVertical: 8 },
    andazebiInputBox: { backgroundColor: colors.background, borderWidth: 2, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, minWidth: 60, alignItems: "center" },
    andazebiInputBoxActive: { borderColor: colors.accent },
    andazebiInputBoxText: { fontSize: 20, color: colors.secondaryText, fontWeight: "700" },
    andazebiInputBoxTextActive: { color: colors.primaryText, fontWeight: "900" },
    overlay: { position: "absolute" as const, top: 0, left: 0, right: 0, bottom: 0, alignItems: "center", backgroundColor: colors.overlay, justifyContent: "center", padding: 24, zIndex: 200 },
    resultCard: { alignItems: "center", backgroundColor: colors.card, borderRadius: 20, elevation: 12, maxWidth: 320, padding: 28, shadowColor: "#000", shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.3, shadowRadius: 16, width: "100%" },
    resultEmoji: { fontSize: 52, marginBottom: 4 },
    resultTitle: { color: colors.primaryText, fontSize: 28, fontWeight: "900", marginBottom: 8, textAlign: "center" },
    resultAnswer: { color: colors.secondaryText, fontSize: 16, fontWeight: "700", marginBottom: 20, textAlign: "center" },
    resultActions: { gap: 10, width: "100%" },
    primaryBtn: { alignItems: "center", backgroundColor: colors.accent, borderRadius: 12, paddingVertical: 14 },
    primaryBtnText: { color: "#fff", fontSize: 16, fontWeight: "900" },
    secondaryBtn: { alignItems: "center", backgroundColor: colors.background, borderColor: colors.border, borderRadius: 12, borderWidth: 1, paddingVertical: 14 },
    secondaryBtnText: { color: colors.primaryText, fontSize: 16, fontWeight: "800" },
  } as const;
}

export type MultiplayerStyles = ReturnType<typeof createMultiplayerStyles>;
