import { StyleSheet } from "react-native";
import { AppColors } from "@/application/providers/theme";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    content: { padding: 24, paddingTop: 12 },
    connectingBox: { alignItems: "center", flex: 1, justifyContent: "center", marginTop: 60, gap: 16 },
    connectingText: { color: colors.secondaryText, fontSize: 16, fontWeight: "600" },
    sectionLabel: { color: colors.primaryText, fontSize: 18, fontWeight: "800", marginBottom: 12 },
    typeSelector: { flexDirection: "row", gap: 8 },
    typePill: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 2,
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
    },
    typePillActive: { borderColor: colors.accent, backgroundColor: colors.accent + "1A" },
    typeText: { color: colors.secondaryText, fontSize: 14, fontWeight: "800" },
    typeTextActive: { color: colors.accent },
    mixHint: {
      backgroundColor: colors.accent + "15",
      borderRadius: 10,
      marginTop: 10,
      padding: 10,
      alignItems: "center",
    },
    mixHintText: { color: colors.accent, fontSize: 13, fontWeight: "700" },
    spacer: { height: 32 },
    primaryBtn: {
      backgroundColor: colors.accent,
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 18,
      gap: 12,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    primaryBtnText: { color: "#fff", fontSize: 18, fontWeight: "900" },
    divider: { flexDirection: "row", alignItems: "center", marginVertical: 32, gap: 16 },
    dividerLine: { flex: 1, height: 1, backgroundColor: colors.border },
    dividerText: { color: colors.secondaryText, fontSize: 14, fontWeight: "700" },
    privateBox: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      padding: 20,
      gap: 16,
    },
    privateLabel: { color: colors.primaryText, fontSize: 16, fontWeight: "800" },
    privateActions: { gap: 12 },
    secondaryBtn: {
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 14,
      gap: 8,
    },
    secondaryBtnText: { color: colors.primaryText, fontSize: 15, fontWeight: "800" },
    joinBox: { flexDirection: "row", gap: 8 },
    input: {
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      color: colors.primaryText,
      flex: 1,
      fontSize: 16,
      fontWeight: "700",
      paddingHorizontal: 16,
      textAlign: "center",
    },
    waitingBox: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      padding: 32,
      marginTop: 20,
      gap: 20,
    },
    waitingText: { color: colors.primaryText, fontSize: 16, fontWeight: "800", textAlign: "center" },
    passcodeBox: { alignItems: "center", gap: 4 },
    passcodeLabel: { color: colors.secondaryText, fontSize: 13, fontWeight: "700" },
    passcodeValue: { color: colors.accent, fontSize: 32, fontWeight: "900", letterSpacing: 4 },
    cancelBtn: {
      backgroundColor: colors.button,
      borderRadius: 12,
      paddingHorizontal: 24,
      paddingVertical: 12,
      width: "100%",
      alignItems: "center",
    },
    cancelBtnText: { color: colors.primaryText, fontSize: 14, fontWeight: "800" },
    pressed: { opacity: 0.7 },
  });
}
