
export {
  BASE_GEORGIAN_KEYBOARD_ROWS,
  BACKSPACE_KEY,
  ENTER_KEY,
  SHIFT_KEY,
  SHIFTED_GEORGIAN_KEYS,
  GEORGIAN_LETTERS,
  QWERTY_TO_GEORGIAN,
  SHIFTED_QWERTY_TO_GEORGIAN,
} from "@/shared/constants/georgianKeyboard";
