import { StyleSheet } from "react-native";
import { AppColors } from "@/application/providers/theme";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      height: 60,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      zIndex: 10,
    },
    headerBtn: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
    headerIcon: { color: colors.primaryText, fontSize: 36, fontWeight: "300", marginTop: -6 },
    headerTitle: { color: colors.primaryText, fontSize: 18, fontWeight: "900" },
    headerSpacer: { width: 44 },
    pressed: { opacity: 0.7 },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 40 },
    cover: { height: 160, width: "100%", backgroundColor: colors.card, position: "relative" },
    coverGradientTop: { position: "absolute", top: 0, left: 0, right: 0, bottom: "50%" },
    coverGradientBottom: { position: "absolute", top: "50%", left: 0, right: 0, bottom: 0 },
    coverOverlay: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,0.15)" },
    avatarRow: {
      flexDirection: "row",
      paddingHorizontal: 20,
      marginTop: -36,
      marginBottom: 20,
      alignItems: "flex-end",
      zIndex: 10,
    },
    avatar: {
      width: 96,
      height: 96,
      borderRadius: 48,
      borderWidth: 4,
      borderColor: colors.background,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      backgroundColor: colors.card,
    },
    avatarImage: { width: 88, height: 88, borderRadius: 44 },
    avatarInitials: { color: "#fff", fontSize: 36, fontWeight: "900" },
    avatarEmoji: { fontSize: 52 },
    heroInfo: { flex: 1, marginLeft: 16, paddingBottom: 4 },
    heroNameRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
    heroName: { color: colors.primaryText, fontSize: 24, fontWeight: "900", flexShrink: 1 },
    rankBadge: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderRadius: 12,
      paddingHorizontal: 6,
      paddingVertical: 2,
      gap: 4,
    },
    rankBadgeIcon: { fontSize: 10 },
    rankBadgeText: { fontSize: 10, fontWeight: "900", textTransform: "uppercase" },
    heroUsername: { color: colors.secondaryText, fontSize: 15, fontWeight: "700" },
    statsBar: {
      flexDirection: "row",
      backgroundColor: colors.card,
      marginHorizontal: 16,
      borderRadius: 16,
      paddingVertical: 16,
      marginBottom: 24,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    statBarItem: { flex: 1, alignItems: "center", gap: 4 },
    statBarNum: { color: colors.primaryText, fontSize: 20, fontWeight: "900" },
    statBarLbl: { color: colors.secondaryText, fontSize: 12, fontWeight: "700" },
    statBarDivider: { width: 1, backgroundColor: colors.border, marginVertical: 4 },
    card: {
      backgroundColor: colors.card,
      marginHorizontal: 16,
      borderRadius: 20,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
    },
    cardTitle: { color: colors.primaryText, fontSize: 18, fontWeight: "900", padding: 20 },
    divider: { height: 1, backgroundColor: colors.border, marginHorizontal: 20 },
    fieldRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 20, paddingVertical: 16 },
    fieldContent: { flex: 1 },
    fieldLabel: { color: colors.secondaryText, fontSize: 13, fontWeight: "700", marginBottom: 4 },
    fieldValue: { color: colors.primaryText, fontSize: 16, fontWeight: "600" },
    achievementsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 16,
      paddingBottom: 16,
      gap: 12,
    },
    achievementBadge: {
      width: "30%",
      backgroundColor: colors.background,
      borderRadius: 16,
      padding: 12,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    achievementBadgeLocked: { opacity: 0.5, backgroundColor: colors.card },
    achievementEmoji: { fontSize: 28, marginBottom: 8 },
    achievementEmojiLocked: { opacity: 0.5 },
    achievementLabel: { color: colors.primaryText, fontSize: 11, fontWeight: "800", textAlign: "center" },
    sectionSubtitle: { color: colors.primaryText, fontSize: 15, fontWeight: "800", marginBottom: 16 },
    distribution: { gap: 8 },
    distributionRow: { flexDirection: "row", alignItems: "center", gap: 12 },
    guessNumber: {
      color: colors.secondaryText,
      fontSize: 14,
      fontWeight: "900",
      width: 16,
      textAlign: "center",
    },
    barTrack: {
      flex: 1,
      height: 28,
      backgroundColor: colors.background,
      borderRadius: 14,
      overflow: "hidden",
    },
    bar: { height: "100%", borderRadius: 14, justifyContent: "center", paddingHorizontal: 12 },
    barText: { color: "#fff", fontSize: 12, fontWeight: "900", textAlign: "right" },
    gameRow: { padding: 20 },
    gameHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 16 },
    gameEmoji: { fontSize: 24 },
    gameLabel: { color: colors.primaryText, fontSize: 16, fontWeight: "900", flex: 1 },
    gamePointsBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
    gamePointsText: { fontSize: 13, fontWeight: "900" },
    gameStats: { flexDirection: "row", gap: 12 },
    gameStatItem: {
      flex: 1,
      backgroundColor: colors.background,
      borderRadius: 12,
      padding: 12,
      alignItems: "center",
    },
    gameStatNum: { color: colors.primaryText, fontSize: 18, fontWeight: "900", marginBottom: 2 },
    gameStatLbl: { color: colors.secondaryText, fontSize: 12, fontWeight: "700" },
    primaryBtn: {
      backgroundColor: colors.accent,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 12,
      marginTop: 16,
    },
    primaryBtnText: { color: "#fff", fontWeight: "bold" },
  });
}
