import { StyleSheet } from "react-native";
import { AppColors } from "@/application/providers/theme";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    header: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 12,
    },
    backBtn: { alignItems: "center", height: 44, justifyContent: "center", width: 44 },
    title: { color: colors.primaryText, fontSize: 18, fontWeight: "900" },
    pressed: { opacity: 0.65 },
    content: { padding: 20, paddingTop: 8 },
    sectionTitle: {
      color: colors.secondaryText,
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 1,
      marginBottom: 8,
      marginTop: 24,
      textTransform: "uppercase",
    },
    card: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      overflow: "hidden",
    },
    separator: { height: 1, backgroundColor: colors.border, marginHorizontal: 16 },
    themeRow: { flexDirection: "row", gap: 8, padding: 12 },
    themeBtn: {
      alignItems: "center",
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 2,
      flex: 1,
      gap: 6,
      paddingVertical: 14,
    },
    themeBtnActive: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "18",
    },
    themeBtnText: { color: colors.secondaryText, fontSize: 12, fontWeight: "700" },
    themeBtnTextActive: { color: colors.accent },
    toggleRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    toggleLeft: { alignItems: "center", flexDirection: "row", gap: 12 },
    toggleLabel: { color: colors.primaryText, fontSize: 16, fontWeight: "600" },
    xpRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      padding: 16,
    },
    xpLabel: { color: colors.secondaryText, fontSize: 13, fontWeight: "700", marginBottom: 2 },
    xpValue: { color: colors.primaryText, fontSize: 22, fontWeight: "900" },
    syncBtn: {
      alignItems: "center",
      backgroundColor: colors.accent,
      borderRadius: 10,
      flexDirection: "row",
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    syncBtnText: { color: "#fff", fontSize: 13, fontWeight: "800" },
    xpHint: {
      color: colors.secondaryText,
      fontSize: 12,
      lineHeight: 17,
      paddingBottom: 14,
      paddingHorizontal: 16,
    },
    infoRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    infoLabel: { color: colors.secondaryText, fontSize: 14, fontWeight: "700" },
    infoValue: { color: colors.primaryText, fontSize: 14, fontWeight: "700" },
    linkRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    linkLeft: { alignItems: "center", flexDirection: "row", gap: 12 },
    linkLabel: { color: colors.primaryText, fontSize: 16, fontWeight: "700" },
    logoutBtn: {
      alignItems: "center",
      backgroundColor: "#e6394618",
      borderColor: "#e63946",
      borderRadius: 14,
      borderWidth: 1,
      flexDirection: "row",
      gap: 10,
      justifyContent: "center",
      marginTop: 32,
      paddingVertical: 16,
    },
    logoutText: { color: "#e63946", fontSize: 16, fontWeight: "800" },

    modalBackdropDialog: { flex: 1, backgroundColor: colors.overlay, justifyContent: "center" },
    dialog: {
      backgroundColor: colors.card,
      borderRadius: 16,
      margin: 24,
      padding: 24,
      alignSelf: "center",
      width: "85%",
      maxWidth: 400,
    },
    dialogIconContainer: {
      alignSelf: "center",
      backgroundColor: "#e6394612",
      borderRadius: 30,
      width: 60,
      height: 60,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 16,
    },
    dialogTitle: {
      color: colors.primaryText,
      fontSize: 18,
      fontWeight: "900",
      marginBottom: 10,
      textAlign: "center",
    },
    dialogText: {
      color: colors.secondaryText,
      fontSize: 15,
      fontWeight: "600",
      marginBottom: 24,
      textAlign: "center",
      lineHeight: 22,
    },
    dialogActions: { flexDirection: "row", gap: 12 },
    dialogCancelBtn: {
      flex: 1,
      backgroundColor: colors.button,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: "center",
    },
    dialogCancelBtnText: { color: colors.primaryText, fontSize: 15, fontWeight: "800" },
    dialogDangerBtn: {
      flex: 1,
      backgroundColor: "#e63946",
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: "center",
    },
    dialogDangerBtnText: { color: "#fff", fontSize: 15, fontWeight: "800" },
  });
}
