import { StyleSheet } from "react-native";
import { AppColors } from "@/application/providers/theme";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    header: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 12,
    },
    backBtn: { alignItems: "center", height: 44, justifyContent: "center", width: 44 },
    headerTitleWrap: {
      position: "absolute",
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      zIndex: -1,
      alignItems: "center",
      justifyContent: "center",
    },
    title: { color: colors.primaryText, fontSize: 18, fontWeight: "900", textAlign: "center" },
    pressed: { opacity: 0.65 },
    pointsBadge: {
      alignItems: "center",
      backgroundColor: colors.accent + "20",
      borderColor: colors.accent,
      borderRadius: 20,
      borderWidth: 1.5,
      flexDirection: "row",
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    pointsText: { color: colors.accent, fontSize: 14, fontWeight: "900" },
    tabRow: {
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    tab: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      flex: 1,
      paddingVertical: 10,
    },
    tabActive: {
      backgroundColor: colors.accent + "1A",
      borderColor: colors.accent,
    },
    tabText: { color: colors.secondaryText, fontSize: 13, fontWeight: "800" },
    tabTextActive: { color: colors.accent },
    center: { flex: 1, alignItems: "center", justifyContent: "center" },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      padding: 16,
    },
    itemCard: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1.5,
      padding: 14,
      width: "47%",
    },
    itemCardEquipped: {
      borderColor: colors.accent,
      backgroundColor: colors.accent + "0D",
    },
    preview: {
      alignItems: "center",
      justifyContent: "center",
      height: 70,
      width: "100%",
      marginBottom: 8,
    },
    previewEmoji: { fontSize: 48 },
    nameTagPreview: {
      borderRadius: 8,
      borderWidth: 2,
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    nameTagText: { fontSize: 16, fontWeight: "900" },
    bannerPreview: {
      borderRadius: 8,
      flexDirection: "row",
      height: 50,
      overflow: "hidden",
      width: "100%",
    },
    bannerStripe: { flex: 1 },
    itemLabel: {
      color: colors.primaryText,
      fontSize: 15,
      fontWeight: "900",
      marginBottom: 2,
      textAlign: "center",
    },
    itemDesc: {
      color: colors.secondaryText,
      fontSize: 11,
      marginBottom: 10,
      textAlign: "center",
    },
    equippedBadge: {
      backgroundColor: colors.accent + "20",
      borderRadius: 8,
      marginBottom: 8,
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    equippedText: { color: colors.accent, fontSize: 11, fontWeight: "800" },
    buyBtn: {
      alignItems: "center",
      backgroundColor: colors.accent,
      borderRadius: 10,
      flexDirection: "row",
      gap: 4,
      paddingHorizontal: 14,
      paddingVertical: 9,
      width: "100%",
      justifyContent: "center",
    },
    buyBtnText: { color: "#fff", fontSize: 15, fontWeight: "900" },
    equipBtn: {
      alignItems: "center",
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 9,
      width: "100%",
    },
    equipBtnActive: {
      backgroundColor: colors.accent + "18",
      borderColor: colors.accent,
    },
    equipBtnText: { color: colors.secondaryText, fontSize: 14, fontWeight: "800", textAlign: "center" },
    equipBtnTextActive: { color: colors.accent },
    previewHint: {
      position: "absolute",
      bottom: 4,
      right: 4,
      backgroundColor: colors.background + "CC",
      borderRadius: 6,
      paddingHorizontal: 5,
      paddingVertical: 2,
    },
    previewHintText: { color: colors.secondaryText, fontSize: 9, fontWeight: "800" },
    previewModalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.65)",
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
    },
    previewModalCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      overflow: "hidden",
      width: "100%",
      maxWidth: 360,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 12,
    },
    confirmModalCard: {
      backgroundColor: colors.card,
      borderRadius: 20,
      width: "100%",
      maxWidth: 340,
      paddingTop: 22,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 12,
    },
    confirmIconWrap: {
      alignItems: "center",
      alignSelf: "center",
      backgroundColor: colors.accent + "20",
      borderRadius: 24,
      height: 48,
      justifyContent: "center",
      marginBottom: 12,
      width: 48,
    },
    confirmTitle: {
      color: colors.primaryText,
      fontSize: 18,
      fontWeight: "900",
      paddingHorizontal: 20,
      textAlign: "center",
    },
    confirmText: {
      color: colors.secondaryText,
      fontSize: 14,
      fontWeight: "700",
      marginBottom: 20,
      marginTop: 6,
      paddingHorizontal: 20,
      textAlign: "center",
    },
    previewMockBanner: {
      height: 100,
      width: "100%",
      position: "relative",
    },
    previewMockAvatarWrap: {
      position: "absolute",
      bottom: -28,
      left: 20,
    },
    previewMockAvatar: {
      width: 60,
      height: 60,
      borderRadius: 30,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 3,
      borderColor: colors.card,
    },
    previewMockAvatarText: { fontSize: 30 },
    previewMockInfo: {
      marginTop: 36,
      paddingHorizontal: 20,
      paddingBottom: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    previewMockName: {
      color: colors.primaryText,
      fontSize: 18,
      fontWeight: "900",
    },
    previewMockTag: {
      borderWidth: 1.5,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    previewMockTagText: { fontSize: 12, fontWeight: "800" },
    previewItemName: {
      color: colors.primaryText,
      fontSize: 16,
      fontWeight: "900",
      paddingHorizontal: 20,
      marginTop: 4,
    },
    previewItemDesc: {
      color: colors.secondaryText,
      fontSize: 13,
      paddingHorizontal: 20,
      marginTop: 2,
      marginBottom: 20,
    },
    previewModalActions: {
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    previewActionBtn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 12,
      paddingVertical: 13,
      flexDirection: "row",
      gap: 6,
    },
    previewActionClose: {
      backgroundColor: colors.button,
      borderColor: colors.border,
      borderWidth: 1,
    },
    previewActionCloseText: { color: colors.primaryText, fontWeight: "800", fontSize: 14 },
    previewActionBuy: { backgroundColor: colors.accent },
    previewActionBuyText: { color: "#fff", fontWeight: "900", fontSize: 14 },
  });
}
