import { StyleSheet } from "react-native";

import { AppColors } from "@/application/providers/theme";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.background },
    header: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingHorizontal: 12,
      paddingVertical: 12,
    },
    backBtn: { alignItems: "center", height: 44, justifyContent: "center", width: 44 },
    title: { color: colors.primaryText, fontSize: 18, fontWeight: "900" },
    pressed: { opacity: 0.7 },
    tabBar: {
      flexDirection: "row",
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingHorizontal: 16,
    },
    tabBtn: {
      alignItems: "center",
      flexDirection: "row",
      gap: 6,
      paddingBottom: 12,
      paddingHorizontal: 12,
      paddingTop: 4,
      position: "relative",
    },
    tabBtnActive: {
      borderBottomWidth: 2,
      borderBottomColor: colors.accent,
    },
    tabBtnText: { color: colors.secondaryText, fontSize: 14, fontWeight: "800" },
    tabBtnTextActive: { color: colors.accent },
    badge: {
      backgroundColor: colors.accent,
      borderRadius: 8,
      minWidth: 16,
      height: 16,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
    },
    badgeText: { color: "#fff", fontSize: 10, fontWeight: "900" },
    content: { padding: 24, paddingTop: 12 },
    connectingBox: { alignItems: "center", flex: 1, justifyContent: "center", marginTop: 60, gap: 16 },
    connectingText: { color: colors.secondaryText, fontSize: 16, fontWeight: "600" },
    sectionLabel: { color: colors.primaryText, fontSize: 18, fontWeight: "800", marginBottom: 12 },
    typeSelector: { flexDirection: "row", gap: 8 },
    typePill: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 2,
      flex: 1,
      paddingVertical: 12,
      alignItems: "center",
    },
    typePillActive: { borderColor: colors.accent, backgroundColor: colors.accent + "1A" },
    typeText: { color: colors.secondaryText, fontSize: 14, fontWeight: "800" },
    typeTextActive: { color: colors.accent },
    mixHint: {
      backgroundColor: colors.accent + "15",
      borderRadius: 10,
      marginTop: 10,
      padding: 10,
      alignItems: "center",
    },
    mixHintText: { color: colors.accent, fontSize: 13, fontWeight: "700" },
    spacer: { height: 32 },
    primaryBtn: {
      backgroundColor: colors.accent,
      borderRadius: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 18,
      gap: 12,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    primaryBtnText: { color: "#fff", fontSize: 18, fontWeight: "900" },
    divider: { flexDirection: "row", alignItems: "center", marginVertical: 32, gap: 16 },
    dividerLine: { flex: 1, height: 1, backgroundColor: colors.border },
    dividerText: { color: colors.secondaryText, fontSize: 14, fontWeight: "700" },
    privateBox: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      padding: 20,
      gap: 16,
    },
    privateLabel: { color: colors.primaryText, fontSize: 16, fontWeight: "800" },
    privateActions: { gap: 12 },
    secondaryBtn: {
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 14,
      gap: 8,
    },
    secondaryBtnText: { color: colors.primaryText, fontSize: 16, fontWeight: "700" },
    joinBox: { flexDirection: "row", gap: 8 },
    input: {
      flex: 1,
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 12,
      borderWidth: 1,
      color: colors.primaryText,
      fontSize: 18,
      fontWeight: "800",
      paddingHorizontal: 16,
      textAlign: "center",
      letterSpacing: 4,
    },
    waitingBox: { alignItems: "center", marginTop: 40, gap: 24 },
    waitingText: { color: colors.primaryText, fontSize: 18, fontWeight: "800" },
    passcodeBox: {
      alignItems: "center",
      backgroundColor: colors.card,
      borderColor: colors.accent,
      borderRadius: 16,
      borderWidth: 2,
      padding: 24,
      width: "100%",
    },
    passcodeLabel: { color: colors.secondaryText, fontSize: 14, fontWeight: "700", marginBottom: 8 },
    passcodeValue: { color: colors.primaryText, fontSize: 48, fontWeight: "900", letterSpacing: 8 },
    cancelBtn: { paddingVertical: 12, paddingHorizontal: 24 },
    cancelBtnText: { color: colors.secondaryText, fontSize: 16, fontWeight: "700" },
    chatContent: { padding: 12, flexGrow: 1 },
    chatEmpty: { flex: 1, alignItems: "center", justifyContent: "center", marginTop: 80 },
    chatEmptyText: { color: colors.secondaryText, fontSize: 15, fontWeight: "600", textAlign: "center" },
    msgRow: { flexDirection: "row", alignItems: "flex-end", marginBottom: 10, gap: 8 },
    msgRowMe: { flexDirection: "row-reverse" },
    msgAvatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    msgAvatarText: { color: "#fff", fontSize: 12, fontWeight: "900" },
    msgBubble: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: 16,
      borderBottomLeftRadius: 4,
      maxWidth: "75%",
      padding: 10,
    },
    msgBubbleMe: {
      backgroundColor: colors.accent + "22",
      borderColor: colors.accent,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 4,
    },
    msgName: { color: colors.accent, fontSize: 11, fontWeight: "800", marginBottom: 2 },
    msgText: { color: colors.primaryText, fontSize: 14, fontWeight: "600" },
    msgTextMe: { color: colors.primaryText },
    msgTime: {
      color: colors.secondaryText,
      fontSize: 10,
      fontWeight: "600",
      marginTop: 4,
      textAlign: "left",
    },
    msgTimeMe: { textAlign: "right" },
    chatInputRow: {
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
    },
    chatInput: {
      flex: 1,
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 22,
      borderWidth: 1,
      color: colors.primaryText,
      fontSize: 15,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    sendBtn: {
      alignItems: "center",
      backgroundColor: colors.accent,
      borderRadius: 22,
      height: 44,
      justifyContent: "center",
      width: 44,
    },
    profileModalBackdrop: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    profileModalCard: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingBottom: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 20,
    },
    profileBanner: {
      height: 80,
      width: "100%",
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    profileAvatarBox: {
      width: 72,
      height: 72,
      borderRadius: 36,
      alignItems: "center",
      justifyContent: "center",
      position: "absolute",
      top: 44,
      left: 24,
      borderWidth: 4,
      borderColor: colors.card,
    },
    profileAvatarText: { color: "#fff", fontSize: 28, fontWeight: "900" },
    profileInfo: {
      marginTop: 44,
      paddingHorizontal: 24,
    },
    profileName: { color: colors.primaryText, fontSize: 20, fontWeight: "900" },
    profileUsername: { color: colors.secondaryText, fontSize: 14, fontWeight: "700", marginTop: 2 },
    profileActions: {
      flexDirection: "row",
      gap: 12,
      paddingHorizontal: 24,
      marginTop: 24,
    },
    profileBtnClose: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
    },
    profileBtnCloseText: { color: colors.primaryText, fontSize: 15, fontWeight: "800" },
    profileBtnAdd: {
      flex: 2,
      backgroundColor: colors.accent,
      paddingVertical: 14,
      borderRadius: 12,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    profileBtnAddText: { color: "#fff", fontSize: 15, fontWeight: "900" },
    profileBtnView: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: colors.card,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
    },
    profileBtnViewText: { color: colors.primaryText, fontSize: 15, fontWeight: "800" },
  });
}
